### PR TITLE
Obsolete legacy openair-mme

### PR DESCRIPTION
**Pull request by rdefosse**
- All tutorials that refer to legacy-mme removed
- ci scripts obsoleted

### CODE REVIEW

**Comment by irfanghauri** [comment]
Seems ok to me @rdefosse

**Review by irfanghauri — APPROVED** [review]

**Review by Vyas20 — APPROVED** [review]

**Comment by Vyas20** [comment]
LGTM

**Comment by rdefosse** [comment]
> LGTM

You are MAGMA-compliant :)

**Review by lionelgo — COMMENTED** [review]
Sure, this obsoletes oai-mme

**Comment by openairinterface-GH** [comment]
LGTM if you are satisfied @rdefosse

**Pull request merged**
